### ISSUE TITLE
Doesn't compile with Elixir 1.3

### ISSUE THREAD

**Issue by jmitchell** [yrashk/exn#8]
First, I notice it's been a long time since the code's been updated. Is this project active, or do you recommend a different project with the same goals? I just stumbled on this and think it's a neat idea.

Anyway, here's the error I'm getting:

```
== Compilation error on file lib/exn/encoder.ex ==
** (CompileError) lib/exn/encoder.ex:1: undefined function defexception/3
    (elixir) lib/kernel/parallel_compiler.ex:117: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```

At some point `defexception/3` must have been deprecated. Now there's only `defexception/1`.

Cheers.

**Comment by yrashk** [comment]
Hi Jacob,

The project is currently unmaintained, but I will gladly accept PRs if anybody still finds this project/idea useful or transfer it to a new maintainer altogether.
